name: Publish release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      deployments: write

    steps:
      - uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: mikepenz/release-changelog-builder-action@f3fc77b47b74e78971fffecb2102ae6eac9a44d6 # v5
        id: build_changelog
        with:
          configuration: .github/changelog.json
          failOnError: "true"
          fetchReviewers: "true"
          fromTag: f36430c1e2593f4517602758296fe567473713da
          toTag: v0.1.0

      - run: |
          cat <<EOF
          CL:
          ${{steps.build_changelog.outputs.changelog}}
          EOF
        

